# Site settings
title: yiqi20200708
description: 和我在一琦
# baseurl: "" # the subpath of your site, e.g. /blog
url: yiqi0708 # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 20200728
user_description: I\'m a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in the <b>crypto-world</b> working for Radix, a London based startup trying to create the next massive scalable DLT. I'm one of the two guys behind all the JS related stuff. Visit my blog here <a href="https://mauriciourraco.com" target="_blank">https://mauriciourraco.com</a>
user_title: 和我在一琦
email: yiqi20200708@outlook.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
